Add POST method , try with postman and have an error #3
ChauPham90/final-project-m6 pull request #4
Opened 2020-02-21 12:10 UTC by ChauPham90

2020-02-21 14:08 UTC, MayaPancake commented on e-commerce/server/models/user.js
> +
whats missing here?

2020-02-21 14:10 UTC, MayaPancake commented on e-commerce/server/models/user.js
> +
you need this: required: true

2020-02-21 14:12 UTC, MayaPancake requested changes
I commented on the code that you are missing.

2020-02-26 09:50 UTC, ChauPham90 commented on e-commerce/server/models/user.js
> +
did u solve it?

2020-02-27 10:13 UTC, merged